name: Merge upstream branches
on:
  push:
      paths-ignore:
      - README.md
      - .github/workflows/rating-chart.yml
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '0 1 * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name '21ki'
          git config --global user.email '21kixc@gmail.com'
          
          git pull --unshallow

          git remote add upstream https://github.com/poswords/EliyaBot.git
          git fetch upstream
          sudo rm -rf data.js
          sudo rm -rf package.json
          sudo rm -rf package-lock.json
          git checkout master
          git merge --no-edit upstream/master
          git push origin master

          
          #sync tag
          git fetch upstream --tags
          git push --tags
          # etc
